steps:
  - label: ':coverage: Test'
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          run: app
  - wait
  - label: ':flashlight: publish @prisma/photon'
    trigger: 'photon-publish'
    build:
      env:
        PUBLISH_PHOTON: 'true'
  - wait
  - label: ':coverage: prisma2-cli-test'
    trigger: 'prisma2-cli-test'
    build:
      env:
        NO_PUBLISH: 'true'
  - wait
  - label: ':gun: publish prisma2'
    trigger: 'prisma2-cli-publish'
    build:
      env:
        PUBLISH_PRISMA2: 'true'
