steps:
  - label: ':coverage: Test Prisma Client JS'
    trigger: 'prisma2-test'
  - label: ':flashlight: Publish Prisma Client JS'
    trigger: 'prisma2-publish'
    if: |
      // Only run on master branch
      // More docs here https://buildkite.com/docs/pipelines/conditionals
      build.branch == 'master'
  - wait
